dbt_transform:
  outputs:
    dev:
      catalog: "workspace"
      host: dbc-b9c0f79b-0d7a.cloud.databricks.com
      http_path: /sql/1.0/warehouses/a530dd632afc2dd0
      schema: "tpch_analytics"
      threads: 6
      token: dapid353b2a92a131b3fbb952a4846324bae
      type: databricks
  target: dev
