dbt_transform:
  outputs:
    dev:
      catalog: ${{ secrets.DATABRICKS_CATALOG }}
      host: ${{ secrets.DATABRICKS_HOST }}
      http_path: ${{ secrets.DATABRICKS_HTTP_PATH }}
      schema: ${{ secrets.DATABRICKS_SCHEMA }}
      threads: 6
      token: ${{ secrets.DATABRICKS_TOKEN }}
      type: databricks
  target: dev
