dbt_transform:
  outputs:
    dev:
      catalog: "{{ env_var('DATABRICKS_CATALOG') }}"
      host: "{{ env_var('DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH') }}"
      schema: "{{ env_var('DATABRICKS_SCHEMA') }}"
      threads: 12
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      type: databricks
  target: dev
