name: dbt-databricks CI/CD

on:
  push:
    branches:
      - "dev"

permissions:
  id-token: write
  contents: read

jobs:
  dbt:
    runs-on: ubuntu-latest
    env:
      DATABRICKS_CATALOG: ${{ secrets.DATABRICKS_CATALOG }}
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_HTTP_PATH: ${{ secrets.DATABRICKS_HTTP_PATH }}
      DATABRICKS_SCHEMA: ${{ secrets.DATABRICKS_SCHEMA }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create virtual environment
        run: |
          echo "Creating Python virtual environment"
          python3 -m venv venv
          source venv/bin/activate
          python3 -m pip install --upgrade pip

      - name: Install dbt and dependencies
        run: |
          source venv/bin/activate
          pip install dbt-core dbt-databricks

      - name: Cache
        uses: actions/cache@v4
        with:
          path: ./venv/
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-

      - name: Run dbt build
        run: |
          source venv/bin/activate
          dbt deps
          dbt compile
          dbt build
